### ISSUE TITLE
Add line comment, Toggle line comment, and Toggle block comment do not work

### ISSUE THREAD

**Issue by isvoboda** [Microsoft/vscode-LaTeX#10]
VSCode 1.3.1
LaTeX 0.1.1

**Comment by xaverh** [comment]
The line comment functionality is provided in pull request #4, which unfortunately has not been accepted yet.
How are block comments in TeX supposed to work?

**Comment by isvoboda** [comment]
One can use `\iffalse comment \fi` but I admit there is no specific notation for block comments in TeX.
