### ISSUE TITLE
Generalize TeX highlighting

### ISSUE THREAD

**Issue by flyx** [Microsoft/vscode-LaTeX#13]
Currently, only a small number of LaTeX commands are highlighted. However, in TeX, any token starting with `\` is a command. So all of these tokens should be highlighted. Currently, they appear to be text content.

Examples of common LaTeX commands not being highlighted:
- `\setlength`
- `\parbox`
- `\vfill`
- `\paperwidth`
- `\makeatletter`

… and so on. It does not seem to be feasible to include all LaTeX commands in the extension, so it should simply highlight all TeX commands. This also would make the bundle more useful for:
- plain TeX
- ConTeXt

**Comment by seanmcbreen** [comment]
Apologies for the delay here - as we have been working hard away at the core of VS Code this extension has gotten very little love.  In part as the community has really stepped up and provided far better LaTeX support.  

As a result of this I just pushed and update deprecating this extension in favor of a community alternative which I suggest you use [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop).


Again sorry for the radio silence here and we hope this will provide you with a much better experience moving forward.  For now I'm closing any open issues and PRs as this extension is no longer under active development.

Sean - VS Code team member
