### ISSUE TITLE
Snippets need fixing, and autocomplete doesn't find labels. 

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode-LaTeX#14]
Apologies for introducing two separate issues at once.

I am on VSCode v1.8, plugin v0.1.3, OSX (Sierra). 

When I type `eq<TAB>`, I get 
```
\begin{equation}
<cursor>
\end{equation}
```
as expected.    
  
However, when I type `ali<TAB>`, I get
```
<cursor>\begin{align`echo TM_SCOPE|grep math|
sed -e 's/.*math.*/ed/'`}

\end{align`echo TM_SCOPE|grep math|
sed -e 's/.*math.*/ed/'`}
```

This aberrant behavior also crops up in the snippet for new environment. Typing `begin<TAB>` gives
```
\begin{env}
  \item )(?2:\item)/
\end{env}
```

I have not extensively tested all snippets; these are just the ones I happened to observe. 

Secondly, please introduce autocompletion for labels (inserting references to equations, subequations, figures and tables). MWE:
```
\begin{equation}
\label{eq:test_eq_1}
x = a + b
\end{equation}

Using equation \ref{eq:<TAB>}
```
Here one hopes that the editor suggests relevant labels for completion.

**Comment by seanmcbreen** [comment]
Apologies for the delay here - as we have been working hard away at the core of VS Code this extension has gotten very little love.  In part as the community has really stepped up and provided far better LaTeX support.  

As a result of this I just pushed and update deprecating this extension in favor of a community alternative which I suggest you use [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop).


Again sorry for the radio silence here and we hope this will provide you with a much better experience moving forward.  For now I'm closing any open issues and PRs as this extension is no longer under active development.

Sean - VS Code team member
