### ISSUE TITLE
Why are quoted strings preceded by a space "invalid.illegal"?

### ISSUE THREAD

**Issue by jacobwalkr** [Microsoft/vscode-LaTeX#16]
Referring to this line and its double-quote buddy: https://github.com/Microsoft/vscode-LaTeX/blob/master/syntaxes/latex.tmLanguage#L1628

Is there a reason that quoted strings preceded by whitespace are considered to be illegal? They seem to be perfectly valid in pdflatex, but perhaps I've missed something :)

This is particularly frustrating in this theme I'm using (which I appreciate isn't your responsibility), which has a bug making all "invalid.illegal" tokens invisible:

![not invalid.illegal](https://cloud.githubusercontent.com/assets/2103207/23406107/3ee35d1c-fdb5-11e6-8aa3-9e7d9c0ae4e8.png)
![invalid.illegal](https://cloud.githubusercontent.com/assets/2103207/23406106/3ee1dd20-fdb5-11e6-8ef3-64572016b932.png)

Forgive me if this isn't the right place to ask!

**Comment by jacobwalkr** [comment]
Naturally, I find my answer right after I submit an issue. Am I right in saying that the "standard" way of doing quotation marks (without using a package like `csquotes`, which I do) is to use backticks `\`` or `\`\`` at the start of the string?

Does that make an opening double quote after a space _illegal_?

**Comment by seanmcbreen** [comment]
Apologies for the delay here - as we have been working hard away at the core of VS Code this extension has gotten very little love.  In part as the community has really stepped up and provided far better LaTeX support.  

As a result of this I just pushed and update deprecating this extension in favor of a community alternative which I suggest you use [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop).


Again sorry for the radio silence here and we hope this will provide you with a much better experience moving forward.  For now I'm closing any open issues and PRs as this extension is no longer under active development.

Sean - VS Code team member
