### ISSUE TITLE
Is it possible to add a snippet for tasks.json configuration?

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-LaTeX#2]
Is it possible to add a snippet to the extension that gets invoked inside a tasks.json file and shows a basic latex->pdf compilation task, with configurations for mac, linux and windows (MikTex) and a problem matcher (comparable to the experience in TexStudio)?

**Comment by felixfbecker** [comment]
Here is an example I'm using:

``` json
{
    "version": "0.1.0",
    "isShellCommand": true,
    "suppressTaskName": true,
    "windows": {
        "command": "powershell",
        "args": ["-Command"],
        "tasks": [
            {
                "taskName": "pdflatex",
                "args": ["cd ${fileDirname}; pdflatex.exe -c-style-errors -synctex=1 -interaction=nonstopmode ${fileBasename}"],
                "showOutput": "silent",
                "isBuildCommand": true,
                "problemMatcher": {
                    "owner": "latex",
                    "fileLocation": ["relative", "${fileDirname}"],
                    "pattern": {
                        "regexp": "^(.*):([0-9]+): (.*)$",
                        "file": 1,
                        "line": 2,
                        "message": 3
                    }
                }
            }
        ]
    }
}
```

**Comment by egamma** [comment]
You can contribute from an extension a snippet to a JSON file. 
However, I think what you really want is  Microsoft/vscode#966

**Comment by seanmcbreen** [comment]
Apologies for the delay here - as we have been working hard away at the core of VS Code this extension has gotten very little love.  In part as the community has really stepped up and provided far better LaTeX support.  

As a result of this I just pushed and update deprecating this extension in favor of a community alternative which I suggest you use [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop).


Again sorry for the radio silence here and we hope this will provide you with a much better experience moving forward.  For now I'm closing any open issues and PRs as this extension is no longer under active development.

Sean - VS Code team member
