### ISSUE TITLE
Add line commenting to the extension

### ISSUE THREAD

**Issue by alceufc** [Microsoft/vscode-LaTeX#5]
Currently the extension does not allow line commenting.

This can be easily fixed though. Please consider this [pull request](https://github.com/Microsoft/vscode-LaTeX/pull/4).

**Comment by Fania** [comment]
Please do consider adding this!
I would really like that.

**Comment by seanmcbreen** [comment]
Apologies for the delay here - as we have been working hard away at the core of VS Code this extension has gotten very little love.  In part as the community has really stepped up and provided far better LaTeX support.  

As a result of this I just pushed and update deprecating this extension in favor of a community alternative which I suggest you use [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop).


Again sorry for the radio silence here and we hope this will provide you with a much better experience moving forward.  For now I'm closing any open issues and PRs as this extension is no longer under active development.

Sean - VS Code team member
