### ISSUE TITLE
something looks wrong with listings

### ISSUE THREAD

**Issue by stone-zeng** [Microsoft/vscode-LaTeX#7]
Something looks wrong with lstlisting environment, just like this:
![default](https://cloud.githubusercontent.com/assets/18233088/16337446/265f2478-3a48-11e6-873b-d14958916901.PNG)
The \begin{...} and \end{...} can't match. Only when using lstlisting, it will happen.

**Comment by seanmcbreen** [comment]
Apologies for the delay here - as we have been working hard away at the core of VS Code this extension has gotten very little love.  In part as the community has really stepped up and provided far better LaTeX support.  

As a result of this I just pushed and update deprecating this extension in favor of a community alternative which I suggest you use [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop).


Again sorry for the radio silence here and we hope this will provide you with a much better experience moving forward.  For now I'm closing any open issues and PRs as this extension is no longer under active development.

Sean - VS Code team member

**Comment by stone-zeng** [comment]
Still thank you for your help. Actually I have turn to LaTeX-Workshop for a long time.
