### ISSUE TITLE
[Feature request] auto close brackets AND beamer colorizer

### ISSUE THREAD

**Issue by yzhang-gh** [Microsoft/vscode-LaTeX#8]
1. Is it possible to automatically close brackets while typing `{`?
2. There is a [LaTex Beamer.plist](https://github.com/textmate/latex.tmbundle/tree/master/Syntaxes) in latex.tmbundle

Thanks.

**Comment by egamma** [comment]
> Is it possible to automatically close brackets while typing {?

@neilsustc you can define a language configuration, pls see: https://github.com/PowerShell/vscode-powershell/blob/master/src/main.ts#L38

**Comment by egamma** [comment]
Assigning to @seanmcbreen this needs to be done in the extension.
