### ISSUE TITLE
Not compatible with default themes Light+ and Dark+

### ISSUE THREAD

**Issue by isvoboda** [Microsoft/vscode-LaTeX#9]
The extension doesn't support default themes: Light+, Dark+.
- highlighting of several LaTex commands in default theme
- highlighting of user defined macros in default theme

**Comment by isvoboda** [comment]
My apologies, it took me a while to realize the problem is the reduced color pallet in mentioned default themes [Tune new colors added for dark+ & light+ themes #1943](https://github.com/Microsoft/vscode/issues/1943l)

Is there any suggestion for a theme supporting the LaTeX highlighting? Ideally for both - light and dark?

I have found the comment suggesting Monokai, but this theme seems quite chaotic, especially during the day.

**Comment by seanmcbreen** [comment]
Apologies for the delay here - as we have been working hard away at the core of VS Code this extension has gotten very little love.  In part as the community has really stepped up and provided far better LaTeX support.  

As a result of this I just pushed and update deprecating this extension in favor of a community alternative which I suggest you use [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop).


Again sorry for the radio silence here and we hope this will provide you with a much better experience moving forward.  For now I'm closing any open issues and PRs as this extension is no longer under active development.

Sean - VS Code team member
